const DEFAULT_PHONE = "+90 534 350 36 30";
const DEFAULT_WHATSAPP = "905343503630";

const PROPERTIES = [
    {
        id: "ALN-101",
        title: "Kleopatra Plajı'na 50m Lüks 2+1 Günlük ve Aylık Kiralık Daire",
        rentalType: "daily",
        rentalTypeBadge: "Günlük / Aylık",
        roomType: "2+1",
        priceDaily: 2500,
        priceMonthly: 45000,
        location: "Alanya Kleopatra Plajı",
        distanceToSea: "50 Metre",
        capacity: "4-5 Kişilik",
        image: "images/img2.jpg",
        badge: "Süper Konum",
        rating: 4.9,
        reviewsCount: 38,
        featured: true,
        features: ["Havuz", "Wi-Fi", "Klima", "Deniz Manzarası", "Balkon", "Asansör", "Full Eşyalı", "7/24 Güvenlik"],
        description: "Alanya Kleopatra Plajı'na sadece 50 metre mesafede, büyüleyici deniz ve Alanya Kalesi manzaralı ultra lüks 2+1 apart daire. Tüm ev gereçleri, klima, yüksek hızlı fiber internet ve havuz imkanı mevcuttur. Günlük ve aylık kiralamaya uygundur."
    },
    {
        id: "ALN-102",
        title: "Damlataş Merkezde 1+1 Günlük Kiralık Modern Apart Daire",
        rentalType: "daily",
        rentalTypeBadge: "Günlük Kiralık",
        roomType: "1+1",
        priceDaily: 1750,
        priceMonthly: 30000,
        location: "Damlataş, Alanya Merkez",
        distanceToSea: "150 Metre",
        capacity: "2-3 Kişilik",
        image: "images/img3.jpg",
        badge: "Fiyat / Performans",
        rating: 4.8,
        reviewsCount: 29,
        featured: true,
        features: ["Wi-Fi", "Klima", "Balkon", "Amerikan Mutfak", "TV / Netflix", "Çamaşır Makinesi", "Merkezi Konum"],
        description: "Alanya Damlataş Mağarası ve plajına yürüme mesafesinde. Çarşıya, restoranlara ve eğlence merkezlerine 2 dakika. Tatiliniz için temiz, hijyenik ve tüm eşyaları eksiksiz 1+1 günlük kiralık daire."
    },
    {
        id: "ALN-103",
        title: "Oba Bölgesinde Site İçi Açık Havuzlu 3+1 Lüks Aylık Kiralık Daire",
        rentalType: "monthly",
        rentalTypeBadge: "Aylık Kiralık",
        roomType: "3+1",
        priceDaily: 4000,
        priceMonthly: 65000,
        location: "Oba Mahallesi, Alanya",
        distanceToSea: "300 Metre",
        capacity: "6-7 Kişilik",
        image: "images/img1.jpg",
        badge: "Site İçi & Havuzlu",
        rating: 5.0,
        reviewsCount: 19,
        featured: true,
        features: ["Açık Havuz", "Çocuk Parkı", "Fitness & Sauna", "Otopark", "Geniş Balkon", "Klima (Her Odada)", "Akıllı Ev"],
        description: "Alanya Oba'nın en nezih sitesinde geniş aileler için ideal 3+1 lüks rezidans daire. Yüzme havuzu, fitness salonu, çocuk oyun alanları ve kapalı otopark ile konforlu aylık veya sezonluk kiralama."
    },
    {
        id: "ALN-104",
        title: "Kalesi & Deniz Manzaralı 3+1 Penthouse Dubleks Apart",
        rentalType: "daily",
        rentalTypeBadge: "Günlük / Aylık VIP",
        roomType: "3+1",
        priceDaily: 4500,
        priceMonthly: 85000,
        location: "Alanya Merkez / Çarşı",
        distanceToSea: "100 Metre",
        capacity: "6 Kişilik",
        image: "images/img4.jpg",
        badge: "VIP Manzara",
        rating: 4.95,
        reviewsCount: 42,
        featured: true,
        features: ["Panoramik Teras", "Jakuzi", "Deniz & Kale Manzarası", "Özel Otopark", "Şömine", "Ultra Lüks Eşyalı"],
        description: "Alanya Kalesi ve Akdeniz'in tüm güzelliğini terasınızdan izleyin. Terasında özel jakuzisi, geniş barbekü alanı ve VIP konforuyla unutulmaz bir Alanya tatili sunan 3+1 dubleks penthouse."
    },
    {
        id: "ALN-105",
        title: "Mahmutlar Sahilde Denize Sıfır 1+1 Günlük ve Aylık Apart",
        rentalType: "daily",
        rentalTypeBadge: "Günlük Kiralık",
        roomType: "1+1",
        priceDaily: 1500,
        priceMonthly: 26000,
        location: "Mahmutlar, Alanya",
        distanceToSea: "Denize Sıfır",
        capacity: "2-4 Kişilik",
        image: "images/img3.jpg",
        badge: "Denize Sıfır",
        rating: 4.7,
        reviewsCount: 22,
        featured: false,
        features: ["Deniz Manzarası", "Açık Havuz", "Wi-Fi", "Klima", "Balkon", "Jeneratör", "Asansör"],
        description: "Mahmutlar Sahil caddesinde, alt geçitle doğrudan plaja bağlanan site içerisinde 1+1 sıfır eşyalı günlük kiralık apart. Tatilciler için ekonomik ve konforlu."
    },
    {
        id: "ALN-106",
        title: "Kestel Sakin Konumda Havuzlu 2+1 Sezonluk Kiralık Daire",
        rentalType: "monthly",
        rentalTypeBadge: "Aylık Kiralık",
        roomType: "2+1",
        priceDaily: 2800,
        priceMonthly: 48000,
        location: "Kestel, Alanya",
        distanceToSea: "200 Metre",
        capacity: "4-5 Kişilik",
        image: "images/img1.jpg",
        badge: "Doğa & Deniz",
        rating: 4.85,
        reviewsCount: 16,
        featured: false,
        features: ["Havuz", "Sauna", "Barbékü Alanı", "Balkon", "Ses Yalıtımı", "Otopark", "Güvenlik"],
        description: "Alanya Kestel'in huzurlu atmosferinde, Dim Çayı'na yakın, denize yürüme mesafesinde lüks sitede eşyalı 2+1 kiralık daire."
    }
];
